---
functional: 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - регистрация пользователя
  - авторизация пользователя
  - возможность выбора количества товара при добавлении в корзину
  - отображение общей суммы товаров в корзине
  - возможность удаления товара из корзины
  - возможность просмотра истории заказов
  - возможность просмотра состояния заказов
  - возможность просмотра отзывов о товаре на странице товара
  - возможность написания отзыва о товаре на странице товара
  - возможность увеличения изображений товара на странице товара
  - отображение сроков доставки товара на странице товара
  - отображение "похожих товаров" на странице товара
  - возможность выбора языка на сайте
  - возможность выбора адреса доставки без регистрации
  - возможность выбора отображения цен на товары в других валютах
  - возвращение "на главную" по клику в шапке на название магазина